from packages import utils, constants
import duckdb

print(utils.CALCULATE_USE_PERCENTAGE(2))
print(utils.CALCULATE_USE_PERCENTAGE(2, until=True))
print(utils.CALCULATE_USE_PERCENTAGE_WITH_AT_LEASE_TWO_LOGGINGS(2))
print(utils.CALCULATE_USE_PERCENTAGE_WITH_AT_LEASE_TWO_LOGGINGS_FROM_LOGGED(2))
print(utils.CALCULATE_USE_PERCENTAGE_INACTIVE_USERS(2))
